Toolkit 11.8 doesn't exist for cluster bigfoot.
[TIME]  Script stats at: 2023-12-13 18:12:58.803303
[PARALLELISM]  The status of cuda is: True.
[PARALLELISM]  The status of MPS is: False.
[PARALLELISM]  There are: 3 devices.
[PARALLELISM]  Parallelism is activated : True
created folder :  /home/conversb/Semantic_Segmentation_U-NET/output/train_13_12_23_part-1
[SAVE]  The config.py file has been saved in the id session folder.
Toolkit 11.8 doesn't exist for cluster bigfoot.
[TIME]  Script stats at: 2023-12-14 14:42:36.858398
[INFO]  You start a process related with the ID: train_14_12_23_part-1
[PARALLELISM]  The status of cuda is: True.
[PARALLELISM]  The status of MPS is: False.
[PARALLELISM]  There are: 3 devices.
[PARALLELISM]  Parallelism is activated : True
[SAVE]  The config.py file has been saved in the id session folder.
[INFO]  Start of model training
[INFO]  Train and test paths spliting...
[INFO]  Saving testing image paths...
[INFO]  Segmentation in Dataset...
[INFO]  found 340 examples in the training set...
[INFO]  found 60 examples in the test set...
[INFO]  Creation of Torch DataLoader...
[INFO]  Training the network...
[INFO]  Start of model training
[INFO]  Train and test paths spliting...
[INFO]  Saving testing image paths...
[INFO]  Segmentation in Dataset...
[INFO]  found 340 examples in the training set...
[INFO]  found 60 examples in the test set...
[INFO]  Creation of Torch DataLoader...
[INFO]  Training the network...
[INFO]  Start of model training
[INFO]  Train and test paths spliting...
[INFO]  Saving testing image paths...
[INFO]  Segmentation in Dataset...
[INFO]  found 340 examples in the training set...
[INFO]  found 60 examples in the test set...
[INFO]  Creation of Torch DataLoader...
[INFO]  Training the network...
[TIME]  Training batch on epoch 0 done at 2023-12-14 14:42:44.965210.
[TIME]  Training batch on epoch 0 done at 2023-12-14 14:42:44.965245.
[TIME]  Training batch on epoch 0 done at 2023-12-14 14:42:44.965223.
[TIME]  Testing batch on epoch 0 done at 2023-12-14 14:47:50.831869.
[TIME]  Testing batch on epoch 0 done at 2023-12-14 14:47:50.900264.
[TIME]  Testing batch on epoch 0 done at 2023-12-14 14:47:50.921481.
[TIME]  EPOCH: 0/50 at 2023-12-14 14:48:45.397560
Train loss: 0.257752, Test loss: 0.2390
[INFO]  We are saving the model at epoch 0.
[TIME]  Training batch on epoch 1 done at 2023-12-14 14:48:45.412387.
[TIME]  EPOCH: 0/50 at 2023-12-14 14:48:48.784311
Train loss: 0.258868, Test loss: 0.2378
[INFO]  We are saving the model at epoch 0.
[TIME]  Training batch on epoch 1 done at 2023-12-14 14:48:48.796082.
[TIME]  EPOCH: 0/50 at 2023-12-14 14:48:50.896815
Train loss: 0.258617, Test loss: 0.2383
[INFO]  We are saving the model at epoch 0.
[TIME]  Training batch on epoch 1 done at 2023-12-14 14:48:50.904925.
[TIME]  Testing batch on epoch 1 done at 2023-12-14 14:53:53.772623.
[TIME]  Testing batch on epoch 1 done at 2023-12-14 14:53:53.842224.
[TIME]  Testing batch on epoch 1 done at 2023-12-14 14:53:53.849259.
[TIME]  EPOCH: 1/50 at 2023-12-14 14:54:46.497538
Train loss: 0.224521, Test loss: 0.2205
[INFO]  We are saving the model at epoch 1.
[TIME]  Training batch on epoch 2 done at 2023-12-14 14:54:46.508763.
[TIME]  EPOCH: 1/50 at 2023-12-14 14:54:50.977059
Train loss: 0.226559, Test loss: 0.2170
[INFO]  We are saving the model at epoch 1.
[TIME]  Training batch on epoch 2 done at 2023-12-14 14:54:50.988064.
[TIME]  EPOCH: 1/50 at 2023-12-14 14:54:51.321537
Train loss: 0.224479, Test loss: 0.2240
[INFO]  We are saving the model at epoch 1.
[TIME]  Training batch on epoch 2 done at 2023-12-14 14:54:51.333687.
[TIME]  Testing batch on epoch 2 done at 2023-12-14 14:59:53.394660.
[TIME]  Testing batch on epoch 2 done at 2023-12-14 14:59:53.577498.
[TIME]  Testing batch on epoch 2 done at 2023-12-14 14:59:53.635554.
[TIME]  EPOCH: 2/50 at 2023-12-14 15:00:45.268207
Train loss: 0.222280, Test loss: 0.2185
[INFO]  We are saving the model at epoch 2.
[TIME]  Training batch on epoch 3 done at 2023-12-14 15:00:45.282088.
[TIME]  EPOCH: 2/50 at 2023-12-14 15:00:50.933782
Train loss: 0.219959, Test loss: 0.2173
[INFO]  We are saving the model at epoch 2.
[TIME]  Training batch on epoch 3 done at 2023-12-14 15:00:50.946462.
[TIME]  EPOCH: 2/50 at 2023-12-14 15:00:52.445325
Train loss: 0.221201, Test loss: 0.2120
[INFO]  We are saving the model at epoch 2.
[TIME]  Training batch on epoch 3 done at 2023-12-14 15:00:52.460309.
[TIME]  Testing batch on epoch 3 done at 2023-12-14 15:05:55.868039.
[TIME]  Testing batch on epoch 3 done at 2023-12-14 15:05:55.917850.
[TIME]  Testing batch on epoch 3 done at 2023-12-14 15:05:55.946926.
[TIME]  EPOCH: 3/50 at 2023-12-14 15:06:51.095493
Train loss: 0.216788, Test loss: 0.2235
[INFO]  We are saving the model at epoch 3.
[TIME]  Training batch on epoch 4 done at 2023-12-14 15:06:51.108696.
[TIME]  EPOCH: 3/50 at 2023-12-14 15:06:51.189547
Train loss: 0.215743, Test loss: 0.2247
[INFO]  We are saving the model at epoch 3.
[TIME]  Training batch on epoch 4 done at 2023-12-14 15:06:51.202513.
[TIME]  EPOCH: 3/50 at 2023-12-14 15:06:53.784706
Train loss: 0.217559, Test loss: 0.2267
[INFO]  We are saving the model at epoch 3.
[TIME]  Training batch on epoch 4 done at 2023-12-14 15:06:53.798346.
[TIME]  Testing batch on epoch 4 done at 2023-12-14 15:11:59.423256.
[TIME]  Testing batch on epoch 4 done at 2023-12-14 15:11:59.423015.
[TIME]  Testing batch on epoch 4 done at 2023-12-14 15:11:59.507301.
[TIME]  EPOCH: 4/50 at 2023-12-14 15:12:54.047473
Train loss: 0.591166, Test loss: 0.2489
[INFO]  We are saving the model at epoch 4.
[TIME]  Training batch on epoch 5 done at 2023-12-14 15:12:54.066078.
[TIME]  EPOCH: 4/50 at 2023-12-14 15:12:55.029914
Train loss: 1.763662, Test loss: 0.2488
[INFO]  We are saving the model at epoch 4.
[TIME]  Training batch on epoch 5 done at 2023-12-14 15:12:55.043066.
[TIME]  EPOCH: 4/50 at 2023-12-14 15:12:56.252845
Train loss: 0.970210, Test loss: 0.2489
[INFO]  We are saving the model at epoch 4.
[TIME]  Training batch on epoch 5 done at 2023-12-14 15:12:56.262156.
[TIME]  Testing batch on epoch 5 done at 2023-12-14 15:17:59.048346.
[TIME]  Testing batch on epoch 5 done at 2023-12-14 15:17:59.199956.
[TIME]  Testing batch on epoch 5 done at 2023-12-14 15:17:59.239157.
[TIME]  EPOCH: 5/50 at 2023-12-14 15:18:51.921301
Train loss: 0.239200, Test loss: 0.2464
[INFO]  We are saving the model at epoch 5.
[TIME]  Training batch on epoch 6 done at 2023-12-14 15:18:51.938214.
[TIME]  EPOCH: 5/50 at 2023-12-14 15:18:55.045315
Train loss: 0.238101, Test loss: 0.2464
[INFO]  We are saving the model at epoch 5.
[TIME]  Training batch on epoch 6 done at 2023-12-14 15:18:55.058023.
[TIME]  EPOCH: 5/50 at 2023-12-14 15:18:56.153885
Train loss: 0.238454, Test loss: 0.2463
[INFO]  We are saving the model at epoch 5.
[TIME]  Training batch on epoch 6 done at 2023-12-14 15:18:56.167008.
[TIME]  Testing batch on epoch 6 done at 2023-12-14 15:23:57.515284.
[TIME]  Testing batch on epoch 6 done at 2023-12-14 15:23:57.656395.
[TIME]  Testing batch on epoch 6 done at 2023-12-14 15:24:02.556548.
[TIME]  EPOCH: 6/50 at 2023-12-14 15:24:51.771525
Train loss: 0.236951, Test loss: 0.2432
[INFO]  We are saving the model at epoch 6.
[TIME]  Training batch on epoch 7 done at 2023-12-14 15:24:51.782289.
[TIME]  EPOCH: 6/50 at 2023-12-14 15:24:51.778582
Train loss: 0.236900, Test loss: 0.2432
[INFO]  We are saving the model at epoch 6.
[TIME]  Training batch on epoch 7 done at 2023-12-14 15:24:51.792099.
[TIME]  EPOCH: 6/50 at 2023-12-14 15:24:55.359429
Train loss: 0.237032, Test loss: 0.2432
[INFO]  We are saving the model at epoch 6.
[TIME]  Training batch on epoch 7 done at 2023-12-14 15:24:55.371608.
[TIME]  Testing batch on epoch 7 done at 2023-12-14 15:29:58.491369.
[TIME]  Testing batch on epoch 7 done at 2023-12-14 15:29:58.612610.
[TIME]  Testing batch on epoch 7 done at 2023-12-14 15:29:58.643910.
[TIME]  EPOCH: 7/50 at 2023-12-14 15:30:53.520056
Train loss: 0.236544, Test loss: 0.2457
[INFO]  We are saving the model at epoch 7.
[TIME]  Training batch on epoch 8 done at 2023-12-14 15:30:53.536660.
[TIME]  EPOCH: 7/50 at 2023-12-14 15:30:54.415079
Train loss: 0.236179, Test loss: 0.2457
[INFO]  We are saving the model at epoch 7.
[TIME]  Training batch on epoch 8 done at 2023-12-14 15:30:54.424984.
[TIME]  EPOCH: 7/50 at 2023-12-14 15:30:55.038444
Train loss: 0.236171, Test loss: 0.2457
[INFO]  We are saving the model at epoch 7.
[TIME]  Training batch on epoch 8 done at 2023-12-14 15:30:55.051200.
[TIME]  Testing batch on epoch 8 done at 2023-12-14 15:35:57.661030.
[TIME]  Testing batch on epoch 8 done at 2023-12-14 15:35:57.757973.
[TIME]  Testing batch on epoch 8 done at 2023-12-14 15:35:57.800716.
[TIME]  EPOCH: 8/50 at 2023-12-14 15:36:52.353902
Train loss: 0.237001, Test loss: 0.2423
[INFO]  We are saving the model at epoch 8.
[TIME]  Training batch on epoch 9 done at 2023-12-14 15:36:52.364668.
[TIME]  EPOCH: 8/50 at 2023-12-14 15:36:53.065953
Train loss: 0.236076, Test loss: 0.2423
[INFO]  We are saving the model at epoch 8.
[TIME]  Training batch on epoch 9 done at 2023-12-14 15:36:53.078900.
[TIME]  EPOCH: 8/50 at 2023-12-14 15:36:54.782806
Train loss: 0.236393, Test loss: 0.2423
[INFO]  We are saving the model at epoch 8.
[TIME]  Training batch on epoch 9 done at 2023-12-14 15:36:54.796398.
[TIME]  Testing batch on epoch 9 done at 2023-12-14 15:41:57.319721.
[TIME]  Testing batch on epoch 9 done at 2023-12-14 15:41:57.390054.
[TIME]  Testing batch on epoch 9 done at 2023-12-14 15:41:57.431112.
[TIME]  EPOCH: 9/50 at 2023-12-14 15:42:51.886250
Train loss: 0.236832, Test loss: 0.2417
[INFO]  We are saving the model at epoch 9.
[TIME]  Training batch on epoch 10 done at 2023-12-14 15:42:51.897390.
[TIME]  EPOCH: 9/50 at 2023-12-14 15:42:52.577348
Train loss: 0.236249, Test loss: 0.2417
[INFO]  We are saving the model at epoch 9.
[TIME]  Training batch on epoch 10 done at 2023-12-14 15:42:52.591577.
[TIME]  EPOCH: 9/50 at 2023-12-14 15:42:53.735708
Train loss: 0.236311, Test loss: 0.2417
[INFO]  We are saving the model at epoch 9.
[TIME]  Training batch on epoch 10 done at 2023-12-14 15:42:53.752344.
[TIME]  Testing batch on epoch 10 done at 2023-12-14 15:47:55.575692.
[TIME]  Testing batch on epoch 10 done at 2023-12-14 15:47:55.582756.
[TIME]  Testing batch on epoch 10 done at 2023-12-14 15:47:55.590103.
[TIME]  EPOCH: 10/50 at 2023-12-14 15:48:45.663413
Train loss: 0.235628, Test loss: 0.2419
[INFO]  We are saving the model at epoch 10.
[TIME]  Training batch on epoch 11 done at 2023-12-14 15:48:45.673957.
[TIME]  EPOCH: 10/50 at 2023-12-14 15:48:52.359001
Train loss: 0.236150, Test loss: 0.2419
[INFO]  We are saving the model at epoch 10.
[TIME]  Training batch on epoch 11 done at 2023-12-14 15:48:52.373414.
[TIME]  EPOCH: 10/50 at 2023-12-14 15:48:53.881203
Train loss: 0.236633, Test loss: 0.2419
[INFO]  We are saving the model at epoch 10.
[TIME]  Training batch on epoch 11 done at 2023-12-14 15:48:53.898589.
[TIME]  Testing batch on epoch 11 done at 2023-12-14 15:53:52.741157.
[TIME]  Testing batch on epoch 11 done at 2023-12-14 15:53:52.749465.
[TIME]  Testing batch on epoch 11 done at 2023-12-14 15:53:52.869369.
[TIME]  EPOCH: 11/50 at 2023-12-14 15:54:39.853141
Train loss: 0.236103, Test loss: 0.2458
[INFO]  We are saving the model at epoch 11.
[TIME]  Training batch on epoch 12 done at 2023-12-14 15:54:40.093129.
[TIME]  EPOCH: 11/50 at 2023-12-14 15:54:49.841867
Train loss: 0.236615, Test loss: 0.2458
[INFO]  We are saving the model at epoch 11.
[TIME]  Training batch on epoch 12 done at 2023-12-14 15:54:49.858414.
[TIME]  EPOCH: 11/50 at 2023-12-14 15:54:50.883068
Train loss: 0.236306, Test loss: 0.2459
[INFO]  We are saving the model at epoch 11.
[TIME]  Training batch on epoch 12 done at 2023-12-14 15:54:50.894327.
[TIME]  Testing batch on epoch 12 done at 2023-12-14 15:59:51.302897.
[TIME]  Testing batch on epoch 12 done at 2023-12-14 15:59:51.314149.
[TIME]  Testing batch on epoch 12 done at 2023-12-14 15:59:51.318090.
[TIME]  EPOCH: 12/50 at 2023-12-14 16:00:40.576638
Train loss: 0.236526, Test loss: 0.2409
[INFO]  We are saving the model at epoch 12.
[TIME]  Training batch on epoch 13 done at 2023-12-14 16:00:40.587952.
[TIME]  EPOCH: 12/50 at 2023-12-14 16:00:47.855788
Train loss: 0.236817, Test loss: 0.2412
[INFO]  We are saving the model at epoch 12.
[TIME]  Training batch on epoch 13 done at 2023-12-14 16:00:47.868685.
[TIME]  EPOCH: 12/50 at 2023-12-14 16:00:48.106549
Train loss: 0.235785, Test loss: 0.2411
[INFO]  We are saving the model at epoch 12.
[TIME]  Training batch on epoch 13 done at 2023-12-14 16:00:48.119620.
[TIME]  Testing batch on epoch 13 done at 2023-12-14 16:05:49.965666.
[TIME]  Testing batch on epoch 13 done at 2023-12-14 16:05:49.975393.
[TIME]  Testing batch on epoch 13 done at 2023-12-14 16:05:50.017697.
[TIME]  EPOCH: 13/50 at 2023-12-14 16:06:40.123183
Train loss: 0.235318, Test loss: 0.2419
[INFO]  We are saving the model at epoch 13.
[TIME]  Training batch on epoch 14 done at 2023-12-14 16:06:40.135744.
[TIME]  EPOCH: 13/50 at 2023-12-14 16:06:46.548944
Train loss: 0.235467, Test loss: 0.2420
[INFO]  We are saving the model at epoch 13.
[TIME]  Training batch on epoch 14 done at 2023-12-14 16:06:46.565199.
[TIME]  EPOCH: 13/50 at 2023-12-14 16:06:47.623308
Train loss: 0.235949, Test loss: 0.2418
[INFO]  We are saving the model at epoch 13.
[TIME]  Training batch on epoch 14 done at 2023-12-14 16:06:47.636639.
[TIME]  Testing batch on epoch 14 done at 2023-12-14 16:11:47.464114.
[TIME]  Testing batch on epoch 14 done at 2023-12-14 16:11:47.514896.
[TIME]  Testing batch on epoch 14 done at 2023-12-14 16:11:47.518247.
[TIME]  EPOCH: 14/50 at 2023-12-14 16:12:39.407506
Train loss: 0.235771, Test loss: 0.2402
[INFO]  We are saving the model at epoch 14.
[TIME]  Training batch on epoch 15 done at 2023-12-14 16:12:39.421262.
[TIME]  EPOCH: 14/50 at 2023-12-14 16:12:43.965366
Train loss: 0.235532, Test loss: 0.2398
[INFO]  We are saving the model at epoch 14.
[TIME]  Training batch on epoch 15 done at 2023-12-14 16:12:43.978542.
[TIME]  EPOCH: 14/50 at 2023-12-14 16:12:45.108462
Train loss: 0.235642, Test loss: 0.2396
[INFO]  We are saving the model at epoch 14.
[TIME]  Training batch on epoch 15 done at 2023-12-14 16:12:45.126180.
[TIME]  Testing batch on epoch 15 done at 2023-12-14 16:17:45.532441.
[TIME]  Testing batch on epoch 15 done at 2023-12-14 16:17:45.541599.
[TIME]  Testing batch on epoch 15 done at 2023-12-14 16:17:45.542985.
[TIME]  EPOCH: 15/50 at 2023-12-14 16:18:36.469848
Train loss: 0.233950, Test loss: 0.2389
[INFO]  We are saving the model at epoch 15.
[TIME]  Training batch on epoch 16 done at 2023-12-14 16:18:36.482656.
[TIME]  EPOCH: 15/50 at 2023-12-14 16:18:43.756926
Train loss: 0.234401, Test loss: 0.2389
[INFO]  We are saving the model at epoch 15.
[TIME]  Training batch on epoch 16 done at 2023-12-14 16:18:43.767467.
[TIME]  EPOCH: 15/50 at 2023-12-14 16:18:43.780843
Train loss: 0.234791, Test loss: 0.2390
[INFO]  We are saving the model at epoch 15.
[TIME]  Training batch on epoch 16 done at 2023-12-14 16:18:43.794331.
[TIME]  Testing batch on epoch 16 done at 2023-12-14 16:23:44.607967.
[TIME]  Testing batch on epoch 16 done at 2023-12-14 16:23:44.703074.
[TIME]  Testing batch on epoch 16 done at 2023-12-14 16:23:44.711638.
[TIME]  EPOCH: 16/50 at 2023-12-14 16:24:37.033429
Train loss: 0.235213, Test loss: 0.2390
[INFO]  We are saving the model at epoch 16.
[TIME]  Training batch on epoch 17 done at 2023-12-14 16:24:37.046776.
[TIME]  EPOCH: 16/50 at 2023-12-14 16:24:42.430670
Train loss: 0.234626, Test loss: 0.2387
[INFO]  We are saving the model at epoch 16.
[TIME]  Training batch on epoch 17 done at 2023-12-14 16:24:42.439787.
[TIME]  EPOCH: 16/50 at 2023-12-14 16:24:43.046292
Train loss: 0.233820, Test loss: 0.2389
[INFO]  We are saving the model at epoch 16.
[TIME]  Training batch on epoch 17 done at 2023-12-14 16:24:43.055463.
[TIME]  Testing batch on epoch 17 done at 2023-12-14 16:29:40.081809.
[TIME]  Testing batch on epoch 17 done at 2023-12-14 16:29:40.107114.
[TIME]  Testing batch on epoch 17 done at 2023-12-14 16:29:45.236576.
[TIME]  EPOCH: 17/50 at 2023-12-14 16:30:33.009156
Train loss: 0.233873, Test loss: 0.2389
[INFO]  We are saving the model at epoch 17.
[TIME]  Training batch on epoch 18 done at 2023-12-14 16:30:33.020032.
[TIME]  EPOCH: 17/50 at 2023-12-14 16:30:36.571685
Train loss: 0.233179, Test loss: 0.2385
[INFO]  We are saving the model at epoch 17.
[TIME]  Training batch on epoch 18 done at 2023-12-14 16:30:36.586092.
[TIME]  EPOCH: 17/50 at 2023-12-14 16:30:38.784144
Train loss: 0.233524, Test loss: 0.2390
[INFO]  We are saving the model at epoch 17.
[TIME]  Training batch on epoch 18 done at 2023-12-14 16:30:38.797962.
[TIME]  Testing batch on epoch 18 done at 2023-12-14 16:35:40.262687.
[TIME]  Testing batch on epoch 18 done at 2023-12-14 16:35:40.270660.
[TIME]  Testing batch on epoch 18 done at 2023-12-14 16:35:40.352374.
[TIME]  EPOCH: 18/50 at 2023-12-14 16:36:34.025901
Train loss: 0.235147, Test loss: 0.2385
[INFO]  We are saving the model at epoch 18.
[TIME]  Training batch on epoch 19 done at 2023-12-14 16:36:34.037722.
[TIME]  EPOCH: 18/50 at 2023-12-14 16:36:35.273086
Train loss: 0.235057, Test loss: 0.2387
[INFO]  We are saving the model at epoch 18.
[TIME]  Training batch on epoch 19 done at 2023-12-14 16:36:35.284359.
[TIME]  EPOCH: 18/50 at 2023-12-14 16:36:37.614854
Train loss: 0.234657, Test loss: 0.2390
[INFO]  We are saving the model at epoch 18.
[TIME]  Training batch on epoch 19 done at 2023-12-14 16:36:37.632863.
[TIME]  Testing batch on epoch 19 done at 2023-12-14 16:41:36.899518.
[TIME]  Testing batch on epoch 19 done at 2023-12-14 16:41:37.002946.
[TIME]  Testing batch on epoch 19 done at 2023-12-14 16:41:37.007945.
[TIME]  EPOCH: 19/50 at 2023-12-14 16:42:28.578661
Train loss: 0.234075, Test loss: 0.2400
[INFO]  We are saving the model at epoch 19.
[TIME]  Training batch on epoch 20 done at 2023-12-14 16:42:28.590014.
[TIME]  EPOCH: 19/50 at 2023-12-14 16:42:33.281826
Train loss: 0.233603, Test loss: 0.2397
[INFO]  We are saving the model at epoch 19.
[TIME]  Training batch on epoch 20 done at 2023-12-14 16:42:33.294810.
[TIME]  EPOCH: 19/50 at 2023-12-14 16:42:33.849829
Train loss: 0.233852, Test loss: 0.2407
[INFO]  We are saving the model at epoch 19.
[TIME]  Training batch on epoch 20 done at 2023-12-14 16:42:33.861616.
[TIME]  Testing batch on epoch 20 done at 2023-12-14 16:47:37.945208.
[TIME]  Testing batch on epoch 20 done at 2023-12-14 16:47:37.992451.
[TIME]  Testing batch on epoch 20 done at 2023-12-14 16:47:38.080668.
[TIME]  EPOCH: 20/50 at 2023-12-14 16:48:32.110092
Train loss: 0.234844, Test loss: 0.2399
[INFO]  We are saving the model at epoch 20.
[TIME]  Training batch on epoch 21 done at 2023-12-14 16:48:32.126004.
[TIME]  EPOCH: 20/50 at 2023-12-14 16:48:33.083777
Train loss: 0.233428, Test loss: 0.2405
[INFO]  We are saving the model at epoch 20.
[TIME]  Training batch on epoch 21 done at 2023-12-14 16:48:33.093265.
[TIME]  EPOCH: 20/50 at 2023-12-14 16:48:35.317810
Train loss: 0.235287, Test loss: 0.2406
[INFO]  We are saving the model at epoch 20.
[TIME]  Training batch on epoch 21 done at 2023-12-14 16:48:35.329998.
[TIME]  Testing batch on epoch 21 done at 2023-12-14 16:53:31.543555.
[TIME]  Testing batch on epoch 21 done at 2023-12-14 16:53:31.646186.
[TIME]  Testing batch on epoch 21 done at 2023-12-14 16:53:31.676058.
[TIME]  EPOCH: 21/50 at 2023-12-14 16:54:26.734108
Train loss: 0.231421, Test loss: 0.2318
[INFO]  We are saving the model at epoch 21.
[TIME]  Training batch on epoch 22 done at 2023-12-14 16:54:26.745901.
[TIME]  EPOCH: 21/50 at 2023-12-14 16:54:27.001075
Train loss: 0.231991, Test loss: 0.2269
[INFO]  We are saving the model at epoch 21.
[TIME]  Training batch on epoch 22 done at 2023-12-14 16:54:27.013611.
[TIME]  EPOCH: 21/50 at 2023-12-14 16:54:29.689606
Train loss: 0.231756, Test loss: 0.2297
[INFO]  We are saving the model at epoch 21.
[TIME]  Training batch on epoch 22 done at 2023-12-14 16:54:29.698797.
[TIME]  Testing batch on epoch 22 done at 2023-12-14 16:59:32.581806.
[TIME]  Testing batch on epoch 22 done at 2023-12-14 16:59:32.642069.
[TIME]  Testing batch on epoch 22 done at 2023-12-14 16:59:32.643922.
[TIME]  EPOCH: 22/50 at 2023-12-14 17:00:26.646938
Train loss: 0.232520, Test loss: 0.2285
[INFO]  We are saving the model at epoch 22.
[TIME]  Training batch on epoch 23 done at 2023-12-14 17:00:26.662954.
[TIME]  EPOCH: 22/50 at 2023-12-14 17:00:29.150877
Train loss: 0.228979, Test loss: 0.2274
[INFO]  We are saving the model at epoch 22.
[TIME]  Training batch on epoch 23 done at 2023-12-14 17:00:29.163847.
[TIME]  EPOCH: 22/50 at 2023-12-14 17:00:29.332531
Train loss: 0.230356, Test loss: 0.2264
[INFO]  We are saving the model at epoch 22.
[TIME]  Training batch on epoch 23 done at 2023-12-14 17:00:29.345732.
[TIME]  Testing batch on epoch 23 done at 2023-12-14 17:05:31.533380.
[TIME]  Testing batch on epoch 23 done at 2023-12-14 17:05:31.612475.
[TIME]  Testing batch on epoch 23 done at 2023-12-14 17:05:41.305743.
[TIME]  EPOCH: 23/50 at 2023-12-14 17:06:25.194133
Train loss: 0.219389, Test loss: 0.2210
[INFO]  We are saving the model at epoch 23.
[TIME]  Training batch on epoch 24 done at 2023-12-14 17:06:25.207403.
[TIME]  EPOCH: 23/50 at 2023-12-14 17:06:25.518107
Train loss: 0.220128, Test loss: 0.2182
[INFO]  We are saving the model at epoch 23.
[TIME]  Training batch on epoch 24 done at 2023-12-14 17:06:25.533887.
[TIME]  EPOCH: 23/50 at 2023-12-14 17:06:30.938478
Train loss: 0.218245, Test loss: 0.2145
[INFO]  We are saving the model at epoch 23.
[TIME]  Training batch on epoch 24 done at 2023-12-14 17:06:30.953197.
[TIME]  Testing batch on epoch 24 done at 2023-12-14 17:11:35.517877.
[TIME]  Testing batch on epoch 24 done at 2023-12-14 17:11:35.588778.
[TIME]  Testing batch on epoch 24 done at 2023-12-14 17:11:35.651603.
[TIME]  EPOCH: 24/50 at 2023-12-14 17:12:30.531917
Train loss: 0.216355, Test loss: 0.2185
[INFO]  We are saving the model at epoch 24.
[TIME]  Training batch on epoch 25 done at 2023-12-14 17:12:30.544028.
[TIME]  EPOCH: 24/50 at 2023-12-14 17:12:31.099141
Train loss: 0.216330, Test loss: 0.2140
[INFO]  We are saving the model at epoch 24.
[TIME]  Training batch on epoch 25 done at 2023-12-14 17:12:31.113534.
[TIME]  EPOCH: 24/50 at 2023-12-14 17:12:32.144346
Train loss: 0.217291, Test loss: 0.2281
[INFO]  We are saving the model at epoch 24.
[TIME]  Training batch on epoch 25 done at 2023-12-14 17:12:32.154482.
[TIME]  Testing batch on epoch 25 done at 2023-12-14 17:17:37.489092.
[TIME]  Testing batch on epoch 25 done at 2023-12-14 17:17:37.491527.
[TIME]  Testing batch on epoch 25 done at 2023-12-14 17:17:37.531195.
+ python main.py
Traceback (most recent call last):
  File "/home/conversb/Semantic_Segmentation_U-NET/model/main.py", line 148, in <module>
    main()
  File "/home/conversb/Semantic_Segmentation_U-NET/model/main.py", line 129, in main
    imagePaths = open(config.TEST_PATHS).read().strip().split("\n")
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/output/train_12_12_23_part-6/test_paths.txt'
+ python main.py

  0%|          | 0/50 [00:00<?, ?it/s]
  2%|▏         | 1/50 [05:31<4:31:01, 331.86s/it]
  4%|▍         | 2/50 [10:50<4:19:22, 324.22s/it]
  6%|▌         | 3/50 [16:42<4:23:59, 337.02s/it]
  8%|▊         | 4/50 [22:11<4:15:45, 333.61s/it]
 10%|█         | 5/50 [27:40<4:09:02, 332.06s/it]
 12%|█▏        | 6/50 [33:59<4:15:15, 348.08s/it]
 14%|█▍        | 7/50 [39:36<4:06:52, 344.49s/it]
 16%|█▌        | 8/50 [44:56<3:55:36, 336.57s/it]
 18%|█▊        | 9/50 [50:38<3:51:14, 338.40s/it]
 20%|██        | 10/50 [56:10<3:44:10, 336.26s/it]
 22%|██▏       | 11/50 [1:01:47<3:38:44, 336.52s/it]
 24%|██▍       | 12/50 [1:07:29<3:34:05, 338.04s/it]
 26%|██▌       | 13/50 [1:13:10<3:29:09, 339.18s/it]
 28%|██▊       | 14/50 [1:18:57<3:24:49, 341.36s/it]
 30%|███       | 15/50 [1:24:38<3:19:01, 341.18s/it]
 32%|███▏      | 16/50 [1:30:17<3:13:07, 340.81s/it]
 34%|███▍      | 17/50 [1:35:49<3:05:57, 338.10s/it]
 36%|███▌      | 18/50 [1:41:18<2:58:45, 335.16s/it]
 38%|███▊      | 19/50 [1:46:52<2:52:58, 334.81s/it]
 40%|████      | 20/50 [1:52:17<2:46:03, 332.11s/it]
 42%|████▏     | 21/50 [1:57:54<2:41:11, 333.51s/it]
 44%|████▍     | 22/50 [2:03:34<2:36:28, 335.31s/it]
 46%|████▌     | 23/50 [2:09:26<2:33:10, 340.40s/it]
 48%|████▊     | 24/50 [2:15:44<2:32:23, 351.69s/it]
 50%|█████     | 25/50 [2:21:43<2:27:30, 354.02s/it]
 52%|█████▏    | 26/50 [2:27:22<2:19:45, 349.39s/it]
 54%|█████▍    | 27/50 [2:33:11<2:13:51, 349.21s/it]
 56%|█████▌    | 28/50 [2:38:33<2:05:01, 340.97s/it]
 58%|█████▊    | 29/50 [2:44:07<1:58:37, 338.93s/it]
 60%|██████    | 30/50 [2:49:24<1:50:49, 332.48s/it]
 62%|██████▏   | 31/50 [2:55:23<1:47:49, 340.49s/it]
 64%|██████▍   | 32/50 [3:00:58<1:41:36, 338.70s/it]
 66%|██████▌   | 33/50 [3:06:22<1:34:42, 334.26s/it]
 68%|██████▊   | 34/50 [3:12:20<1:31:02, 341.43s/it]
 70%|███████   | 35/50 [3:17:54<1:24:50, 339.36s/it]
 72%|███████▏  | 36/50 [3:23:42<1:19:45, 341.79s/it]
 74%|███████▍  | 37/50 [3:29:17<1:13:38, 339.89s/it]
 76%|███████▌  | 38/50 [3:34:35<1:06:40, 333.36s/it]
 78%|███████▊  | 39/50 [3:40:44<1:03:03, 343.92s/it]
 80%|████████  | 40/50 [3:46:45<58:10, 349.03s/it]  
 82%|████████▏ | 41/50 [3:52:42<52:42, 351.35s/it]
 84%|████████▍ | 42/50 [3:58:43<47:13, 354.20s/it]
 86%|████████▌ | 43/50 [4:04:13<40:28, 346.98s/it]
 88%|████████▊ | 44/50 [4:09:42<34:09, 341.57s/it]
 90%|█████████ | 45/50 [4:15:14<28:14, 338.88s/it]
 92%|█████████▏| 46/50 [4:20:47<22:28, 337.08s/it]
 94%|█████████▍| 47/50 [4:26:47<17:11, 344.00s/it]
 96%|█████████▌| 48/50 [4:32:29<11:26, 343.16s/it]
 98%|█████████▊| 49/50 [4:38:45<05:53, 353.25s/it]
100%|██████████| 50/50 [4:44:46<00:00, 355.34s/it]
100%|██████████| 50/50 [4:44:46<00:00, 341.72s/it]
+ python main.py
Traceback (most recent call last):
  File "/home/conversb/Semantic_Segmentation_U-NET/model/main.py", line 148, in <module>
    main()
  File "/home/conversb/Semantic_Segmentation_U-NET/model/main.py", line 97, in main
    mp.spawn(funcParallelism, args=(config.NBR_GPU,), nprocs=config.NBR_GPU)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/conversb/Semantic_Segmentation_U-NET/model/main.py", line 17, in funcParallelism
    torchvision.transforms.RandomResizedCrop(size=(224, 224), antialias=True),
TypeError: __init__() got an unexpected keyword argument 'antialias'

+ python main.py

  0%|          | 0/50 [00:00<?, ?it/s]
  0%|          | 0/50 [00:00<?, ?it/s]
  0%|          | 0/50 [00:00<?, ?it/s]
  2%|▏         | 1/50 [06:00<4:54:21, 360.45s/it]
  2%|▏         | 1/50 [06:03<4:57:07, 363.83s/it]
  2%|▏         | 1/50 [06:05<4:58:51, 365.94s/it]
  4%|▍         | 2/50 [12:01<4:48:11, 360.23s/it]
  4%|▍         | 2/50 [12:06<4:50:46, 363.46s/it]
  4%|▍         | 2/50 [12:06<4:50:09, 362.70s/it]
  6%|▌         | 3/50 [18:00<4:41:39, 359.57s/it]
  6%|▌         | 3/50 [18:05<4:43:00, 361.29s/it]
  6%|▌         | 3/50 [18:07<4:44:00, 362.55s/it]
  8%|▊         | 4/50 [24:06<4:36:46, 361.01s/it]
  8%|▊         | 4/50 [24:06<4:37:35, 362.07s/it]
  8%|▊         | 4/50 [24:08<4:37:27, 361.91s/it]
 10%|█         | 5/50 [30:09<4:30:59, 361.32s/it]
 10%|█         | 5/50 [30:10<4:32:02, 362.71s/it]
 10%|█         | 5/50 [30:11<4:31:52, 362.51s/it]
 12%|█▏        | 6/50 [36:06<4:24:32, 360.73s/it]
 12%|█▏        | 6/50 [36:10<4:24:54, 361.24s/it]
 12%|█▏        | 6/50 [36:11<4:25:09, 361.58s/it]
 14%|█▍        | 7/50 [42:06<4:17:44, 359.63s/it]
 14%|█▍        | 7/50 [42:06<4:17:50, 359.77s/it]
 14%|█▍        | 7/50 [42:10<4:19:09, 361.62s/it]
 16%|█▌        | 8/50 [48:08<4:12:16, 360.40s/it]
 16%|█▌        | 8/50 [48:09<4:12:33, 360.80s/it]
 16%|█▌        | 8/50 [48:10<4:12:33, 360.79s/it]
 18%|█▊        | 9/50 [54:07<4:05:56, 359.91s/it]
 18%|█▊        | 9/50 [54:08<4:06:05, 360.13s/it]
 18%|█▊        | 9/50 [54:09<4:06:18, 360.46s/it]
 20%|██        | 10/50 [1:00:06<3:59:51, 359.79s/it]
 20%|██        | 10/50 [1:00:07<3:59:57, 359.94s/it]
 20%|██        | 10/50 [1:00:08<3:59:59, 360.00s/it]
 22%|██▏       | 11/50 [1:06:00<3:52:40, 357.95s/it]
 22%|██▏       | 11/50 [1:06:07<3:53:43, 359.58s/it]
 22%|██▏       | 11/50 [1:06:08<3:54:13, 360.36s/it]
 24%|██▍       | 12/50 [1:11:55<3:46:01, 356.88s/it]
 24%|██▍       | 12/50 [1:12:04<3:47:19, 358.94s/it]
 24%|██▍       | 12/50 [1:12:05<3:47:34, 359.34s/it]
 26%|██▌       | 13/50 [1:17:55<3:40:44, 357.97s/it]
 26%|██▌       | 13/50 [1:18:02<3:41:10, 358.66s/it]
 26%|██▌       | 13/50 [1:18:03<3:41:11, 358.70s/it]
 28%|██▊       | 14/50 [1:23:55<3:35:04, 358.45s/it]
 28%|██▊       | 14/50 [1:24:01<3:35:10, 358.62s/it]
 28%|██▊       | 14/50 [1:24:02<3:35:23, 358.99s/it]
 30%|███       | 15/50 [1:29:54<3:29:14, 358.70s/it]
 30%|███       | 15/50 [1:29:59<3:28:56, 358.19s/it]
 30%|███       | 15/50 [1:30:00<3:29:11, 358.60s/it]
 32%|███▏      | 16/50 [1:35:51<3:22:59, 358.21s/it]
 32%|███▏      | 16/50 [1:35:58<3:23:14, 358.67s/it]
 32%|███▏      | 16/50 [1:35:58<3:23:13, 358.62s/it]
 34%|███▍      | 17/50 [1:41:52<3:17:24, 358.92s/it]
 34%|███▍      | 17/50 [1:41:57<3:17:16, 358.67s/it]
 34%|███▍      | 17/50 [1:41:58<3:17:20, 358.81s/it]
 36%|███▌      | 18/50 [1:47:48<3:10:57, 358.03s/it]
 36%|███▌      | 18/50 [1:47:51<3:10:31, 357.23s/it]
 36%|███▌      | 18/50 [1:47:53<3:10:55, 357.98s/it]
 38%|███▊      | 19/50 [1:53:49<3:05:26, 358.93s/it]
 38%|███▊      | 19/50 [1:53:50<3:04:47, 357.67s/it]
 38%|███▊      | 19/50 [1:53:52<3:05:05, 358.24s/it]
 40%|████      | 20/50 [1:59:43<2:58:48, 357.61s/it]
 40%|████      | 20/50 [1:59:48<2:58:53, 357.77s/it]
 40%|████      | 20/50 [1:59:48<2:58:48, 357.63s/it]
 42%|████▏     | 21/50 [2:05:47<2:52:56, 357.82s/it]
 42%|████▏     | 21/50 [2:05:48<2:53:50, 359.68s/it]
 42%|████▏     | 21/50 [2:05:50<2:53:32, 359.05s/it]
 44%|████▍     | 22/50 [2:11:41<2:47:00, 357.87s/it]
 44%|████▍     | 22/50 [2:11:42<2:46:34, 356.94s/it]
 44%|████▍     | 22/50 [2:11:44<2:46:54, 357.65s/it]
 46%|████▌     | 23/50 [2:17:41<2:40:50, 357.44s/it]
 46%|████▌     | 23/50 [2:17:44<2:41:39, 359.24s/it]
 46%|████▌     | 23/50 [2:17:44<2:41:21, 358.56s/it]
 48%|████▊     | 24/50 [2:23:40<2:35:02, 357.77s/it]
 48%|████▊     | 24/50 [2:23:40<2:35:17, 358.38s/it]
 48%|████▊     | 24/50 [2:23:45<2:35:46, 359.47s/it]
 50%|█████     | 25/50 [2:29:45<2:30:01, 360.04s/it]
 50%|█████     | 25/50 [2:29:46<2:29:51, 359.68s/it]
 50%|█████     | 25/50 [2:29:47<2:30:21, 360.85s/it]Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
Traceback (most recent call last):
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    exitcode = _main(fd, parent_sentinel)
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'

 50%|█████     | 25/50 [2:34:53<2:34:53, 371.73s/it]

 50%|█████     | 25/50 [2:34:53<2:34:53, 371.73s/it]

 50%|█████     | 25/50 [2:34:53<2:34:53, 371.73s/it]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/conversb/.conda/envs/torch/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conversb/Semantic_Segmentation_U-NET/model/main.py'
Traceback (most recent call last):
  File "/home/conversb/Semantic_Segmentation_U-NET/model/main.py", line 150, in <module>
  File "/home/conversb/Semantic_Segmentation_U-NET/model/main.py", line 99, in main
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2647504) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/conversb/Semantic_Segmentation_U-NET/model/main.py", line 45, in funcParallelism
  File "/home/conversb/Semantic_Segmentation_U-NET/model/train.py", line 286, in trainModel
  File "/home/conversb/Semantic_Segmentation_U-NET/model/train.py", line 196, in batchTesting
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1315, in _get_data
    success, data = self._try_get_data()
  File "/home/conversb/.conda/envs/torch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1176, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 2647373, 2647375, 2647378, 2647381, 2647384, 2647454, 2647457, 2647462, 2647466, 2647472, 2647477, 2647480, 2647483, 2647486, 2647490, 2647493, 2647496, 2647498, 2647501, 2647504, 2647507, 2647510, 2647513, 2647516) exited unexpectedly

